Repository codegasms/langsuit, pull requests merged in 2024-09, with the labels that each got.

#4 [Init] [Done] [Parth] Initialized drizzle with neon
  langsuit/app/api/auth/signin/route.ts
  langsuit/app/api/auth/signup/route.ts
  langsuit/app/api/courses/route.ts
  langsuit/app/models/schemas.ts
  langsuit/db/drizzle.ts
  langsuit/db/schema.ts
  langsuit/drizzle.config.ts
  langsuit/next.config.mjs
  langsuit/package-lock.json
  langsuit/package.json
  langsuit/tsconfig.json
  langsuit/utils/dbOrchestrator.ts
Labels: enhancement, bugfix

#20 Feature/authentication
  langsuit/app/(landing)/footer.tsx
  langsuit/app/(landing)/header.tsx
  langsuit/app/(landing)/layout.tsx
  langsuit/app/(landing)/page.tsx
  langsuit/app/layout.tsx
  langsuit/app/page.tsx
  langsuit/app/sign-in/[[...sign-in]]/page.tsx
  langsuit/app/sign-up/[[...sign-up]]/page.tsx
  langsuit/middleware.ts
  langsuit/package-lock.json
  langsuit/package.json
Labels: enhancement, frontend, backend

#21 Feature/landing
  langsuit/app/(landing)/footer.tsx
  langsuit/app/(landing)/header.tsx
  langsuit/app/(landing)/page.tsx
  langsuit/app/layout.tsx
  langsuit/public/CN - China.svg
  langsuit/public/ES - Spain.svg
  langsuit/public/FR - France.svg
  langsuit/public/IN - India.svg
  langsuit/public/JP - Japan.svg
  langsuit/public/KR - Korea (South).svg
  langsuit/public/RU - Russian Federation.svg
  langsuit/public/SA - Saudi Arabia.svg
  langsuit/public/US - United States.svg
  langsuit/public/langsuit.png
Labels: enhancement, frontend

#24 Feature/homepage
  langsuit/app/(home)/layout.tsx
  langsuit/app/(home)/learn/header.tsx
  langsuit/app/(home)/learn/page.tsx
  langsuit/app/globals.css
  langsuit/components/feed-wrapper.tsx
  langsuit/components/mobile-header.tsx
  langsuit/components/mobile-sidebar.tsx
  langsuit/components/sidebar-item.tsx
  langsuit/components/sidebar.tsx
  langsuit/components/sticky-wrapper.tsx
  langsuit/components/ui/sheet.tsx
  langsuit/components/user-progress.tsx
  langsuit/package-lock.json
  langsuit/package.json
  langsuit/public/alphabets.svg
  langsuit/public/hearts.svg
  langsuit/public/leaderboard.svg
  langsuit/public/learn.svg
  langsuit/public/points.svg
  langsuit/public/quest.svg
  langsuit/public/shop.svg
Labels: enhancement, frontend

#32 [Feat] [Done] [Manikanta] Add alphabets page with Backend route
  langsuit/app/(home)/alphabets/alpha-search.tsx
  langsuit/app/(home)/alphabets/page.tsx
  langsuit/lib/mongodb.ts
  langsuit/models/language.ts
  langsuit/package-lock.json
  langsuit/package.json
  langsuit/pages/api/alphabets.ts
  langsuit/pages/api/seed.ts
Labels: enhancement, frontend, backend

#31 [Feat] [Done] [Bishwajeet] Add Feedback Page with REGEX Validation
  langsuit/app/(home)/feedback/feedbackForm.tsx
  langsuit/app/(home)/feedback/page.tsx
  langsuit/components/sidebar.tsx
  langsuit/public/feedback.svg
Labels: enhancement, frontend

#29 Feature/courses
  langsuit/actions/user-progress.ts
  langsuit/app/(home)/courses/card.tsx
  langsuit/app/(home)/courses/list.tsx
  langsuit/app/(home)/courses/loading.tsx
  langsuit/app/(home)/courses/page.tsx
  langsuit/app/(home)/learn/loading.tsx
  langsuit/app/(home)/learn/page.tsx
  langsuit/app/layout.tsx
  langsuit/components/ui/sonner.tsx
  langsuit/db/migrations/0000_regular_glorian.sql
  langsuit/db/migrations/meta/0000_snapshot.json
  langsuit/db/migrations/meta/_journal.json
  langsuit/db/queries.ts
  langsuit/package-lock.json
  langsuit/package.json
  langsuit/public/mascot.svg
Labels: enhancement, frontend, backend

#26 [Add] [Done] [Parth] Added Instructor dashboard (using dummy data)
  langsuit/app/(dashboard)/instructor/[username]/(home)/page.tsx
  langsuit/app/(dashboard)/instructor/[username]/chat/page.tsx
  langsuit/app/(dashboard)/instructor/[username]/community/page.tsx
  langsuit/app/(dashboard)/instructor/[username]/engagement/page.tsx
  langsuit/app/(dashboard)/instructor/[username]/keys/page.tsx
  langsuit/app/(dashboard)/instructor/[username]/layout.tsx
  langsuit/app/(dashboard)/instructor/[username]/livestream/page.tsx
  langsuit/app/(dashboard)/instructor/[username]/revenue/page.tsx
  langsuit/app/(dashboard)/instructor/_components/navigation/index.tsx
  langsuit/app/(dashboard)/instructor/_components/sidebar/nav-item.tsx
  langsuit/components/ui/card.tsx
  langsuit/utils/dbOrchestrator.ts
Labels: enhancement, frontend, backend

#25 Feature/quests
  langsuit/app/(dashboard)/user/[username]/(home)/_components/Languages.tsx
  langsuit/app/(dashboard)/user/[username]/(home)/_components/Leaderboard.tsx
  langsuit/app/(dashboard)/user/[username]/(home)/_components/Progress.tsx
  langsuit/app/(dashboard)/user/[username]/(home)/_components/QuestsPage.tsx
  langsuit/app/(dashboard)/user/[username]/(home)/_components/YourProgress.tsx
  langsuit/app/(dashboard)/user/[username]/(home)/page.tsx
  langsuit/app/(dashboard)/user/[username]/languages/[languageID]/page.tsx
  langsuit/app/(dashboard)/user/[username]/languages/page.tsx
  langsuit/app/(dashboard)/user/[username]/layout.tsx
  langsuit/app/(dashboard)/user/[username]/leaderboard/page.tsx
  langsuit/app/(dashboard)/user/[username]/progress/page.tsx
  langsuit/app/(dashboard)/user/[username]/quests/page.tsx
  langsuit/app/(dashboard)/user/_components/container/index.tsx
  langsuit/app/(dashboard)/user/_components/navbar/index.tsx
  langsuit/app/(dashboard)/user/_components/navbar/logo.tsx
  langsuit/app/(dashboard)/user/_components/navigation/index.tsx
  langsuit/app/(dashboard)/user/_components/sidebar/index.tsx
  langsuit/app/(dashboard)/user/_components/sidebar/nav-item.tsx
  langsuit/app/(dashboard)/user/_components/sidebar/toggle.tsx
  langsuit/app/(dashboard)/user/_components/sidebar/wrapper.tsx
  langsuit/app/api/leaderboard/read/route.ts
  langsuit/app/api/leaderboard/route.ts
  langsuit/app/api/progress/read/route.ts
  langsuit/app/api/quests/delete.ts
  langsuit/app/api/quests/read/route.ts
  langsuit/app/api/quests/update.ts
  langsuit/app/api/user/[username]/languages/[languageId]/route.ts
  langsuit/app/api/user/[username]/languages/route.ts
  langsuit/app/api/user/[username]/progress/route.ts
  langsuit/app/api/user/[username]/quests.ts
  langsuit/app/api/user/[username]/quests/route.ts
  langsuit/app/main/quests/page.tsx
  langsuit/package-lock.json
  langsuit/package.json
Labels: enhancement, frontend, backend
